sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t image-sequencer-app .
  - docker-compose build

script: docker-compose run image-sequencer-app bash -c "NODE_ENV=development npm install && npm test"
os:
  - linux
  # - osx : No docker support
