steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/public-lab/image-sequencer-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/public-lab/image-sequencer-app']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/image-sequencer-app', '*=gcr.io/public-lab/image-sequencer-app']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=mapknitter'
images: ['gcr.io/public-lab/image-sequencer-app']
