version: '2.1'

services:
  image-sequencer-app:
    image: image-sequencer-app
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 src/server.js